### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Colintsl** [linh-gist/3D-Visual-MOT#1]
Hi，Great work，I‘d like to reproduce it. Could you put CMC datasets on Google Drive？thank U.

**Comment by linh-gist** [comment]
Hi @Colintsl, thank you for your interest in our work.

We will try to push the dataset to OneDrive or GoogleDrive permanently, in the meanwhile you can try to download the dataset from MEGA CLOUD, NZ. as mentioned in the README file (the download speed is slow).

https://mega.nz/file/LKxAyZiT#wa-aMQmgk9guNkjj1olaPeUf-LgPS5P9iYBmZSLFnp8

**Comment by linh-gist** [comment]
Google Drive is ready, you can download it from now

https://drive.google.com/file/d/1eliDg_DTHqgW10ww7aQWvicAwP3hlVEo/view?usp=sharing

**Comment by Colintsl** [comment]
The Mesa cloud is not  free, but I have now **solved the problem** and successfully reproduced the work using your data. Thank you. 

I now want to run the code on my own scenario now. There are 3 cameras in the scene, collecting videos from 3 perspectives, but there is no calibration information for the cameras.

**Could you help me know what data-related work I should do to adapt the input of the code?** 
I observed that :  
1. there is .npz format information in the dataset, and there are also .mat format data under .../ms_glmb_ukf/cmc/      
2. there are some parameters for the camera and dataset in gen_model.py
4. the  data input is actually a sequence of numbered PNG format images, not direct MP4.

I want to know what I should do for input adaptation. I already have three MP4 format video files. Currently, my plan is to first extract frame images into PNG format and then process them into. npz,. mat format, but I don't know how to do it specifically? Can you tell me about the tools or processes you handle? Thank you very much.

Additionally, do you have any suggestions for directly **processing video streams** with code? The paper mentions the advantage of being able to adapt to the camera。Does this **requires knowledge of the camera's intrinsic parameters and the extrinsic relationships with other cameras**? because I saw in gen_model.py that some configuration parameters are specifically set for a certain dataset, such as WILDTRACK.
