### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by Colintsl** [linh-gist/3D-Visual-MOT#2]
Thank you for your excellent work. As a newcomer to the field of multi-camera Multiple Object Tracking (MoT) research, I would appreciate your assistance with the following questions:

**Q1:** I am working with a scene that is captured by three cameras, each providing a unique perspective, but unfortunately, there is no calibration data available for these cameras.
**What data-related tasks should I undertake to adapt the code for my input?﻿
How should I preprocess my data to align with the algorithm's requirement**s?

Here are my observations and current understanding:

1. The dataset includes .npz files and also .mat files located in the directory .../ms_glmb_ukf/cmc/.
2. There are parameters within gen_model.py that pertain to the camera setup and the dataset specifics.
3. The actual data input is a sequence of numbered PNG images, not raw MP4 video files.

For input adaptation, my plan is to first convert the MP4 video files into a sequence of PNG images by ffmpeg and then format them into .npz and .mat files. However, I am unsure of the specific steps or tools required for this conversion. Could you provide guidance on the tools or processes to achieve this? I would greatly appreciate your assistance.

Is the code based on the FairMoT 2D and CSTrack 2D frameworks? I suspect that the .npz format data might be an output of these frameworks. Is this correct? If so, does this framework not support online processing?
﻿
**Q2:** Furthermore, do you have any recommendations for directly processing video streams with the code? The paper highlights the benefits of adapting to different camera setups. Does this adaptation require knowledge of the camera's intrinsic parameters and the extrinsic relationships with other cameras? I've noticed in gen_model.py that certain configuration parameters are tailored for specific datasets, such as WILDTRACK

**Comment by linh-gist** [comment]
Hi, I have seen your question posted in #1 but I was busy with other work and could not answer your questions immediately.

**Answer Q1**:  

- NPZ files are detection files outputted from FairMOT and CSTrack. These detectors can process output in real time if you run on fast GPUs or CPUs.
- My algorithm requires intrinsic and extrinsic camera parameters to project from 3D to image plane (Unscented Transform) and image to 3D (homogenous transform).
- Images in the CMC dataset are captured with 4 FPS while the WILDTRACK dataset was captured at 2 FPS, these means that objects are moving faster within two adjacent frames. If your camera supports 30FPS, you can only capture frame indices 1, 7, 14, and 28 and ignore the rest. Then, you run my algorithm with parameters in `gen_model.py` without any modification.
- If you have your input is a video, you can just use OpenCV to read frames from the video and use DeepLearning detectors such as FairMOT, CSTrack to obtain detection (you do not need to use FFMPEG).


**Answer Q2**:  
- You can do it in real-time if you have a fast computer to detector objects. You need to read frame-by-frame from cameras => detect object => run my algorithm. Note that, all frames captured from cameras need to be synchronous.
- You need to know calibration matrices of all cameras. To obtain it, you can follow this guide [camera-calibration-with-opencv](https://medium.com/analytics-vidhya/camera-calibration-with-opencv-f324679c6eb7).

**Comment by Colintsl** [comment]
Wow, thank you very much! Now I have a clear understanding of the next steps and am full of motivation. Thank you again, for the great work and being a nice person.
